reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
os:
  - osx
  - windows
  - *reference_os
dist: bionic
addons:
  apt:
    packages:
    - graphviz
stages:
  - check
  - test
  - deploy
env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/maven-central-gradle-plugin"
  matrix:
    - *reference_jdk
    - JDK="adopt-openj9@1.8"
    - JDK="adopt@1.11"
    - JDK="adopt-openj9@1.11"
    - JDK="adopt@1.12"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - ./gradlew clean check
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        # Central
        - secure: "t8uGlczu+5hijK8K9aS9QV4BWM4v1jGoWSN1lhI45rg9JAT9Y3ywYO9gsq2hc+dQbnsk205X875kVzPE4jdRyUAfRby6+DbsTdeZ0W8ooTGt6p3CAyMmrhjrdqyjEC7Q+AH1/IccrDrWdh70u2dYCFkOEXWg6N+WFXazAoKOG1F7RB2F1mlnvIz7aqQYiPUc+ccXtyB8HiTswMSrOhLgQtuXsPKyOjuL9q4lHzL2rFwH3II+BvuqfxlgvftWOnRNiOGm6AKq+TzhEQ3PckToAXwT3mb7BZrM5F4E3dRekVnC9WgFcYIdr8TWPBB1QTqlfmhCDSXB775xdrlSwaDvtim1rknrAOc1ijVYWMxVhmTPq+HHYPbYa5nYj3e9LCQWFssJMc9GIf2HsGymvAnEDD6noXA0gRLAIKX6yeb3eWjUNYVGEmseFNGRvdmIbzwUligmRvW0kdtSiLjGg4LykZlFBK/G/Jw9XoQ+qjKA41daMO5MeVYUPhXmrJMqf7QcRUqeNmKVmQBZ+JgttQDH7sSkx9dbaXMWj8KOabdoTlBqKsESuC3HafpbPcVk0y4aufLh9pinPJJAg8Y1ar7rpoORAOh15NI4kDLHLYQ8Q4q7gq3bLidoSxnv2idz+DZnuA6EL++A5a/8jqTGHcnVusCzDwNXpntoYoUc82GhKV0="
        - secure: "hNiKXYZhSj00CcUM8rdWfGVdjvp5DKwlcmZGwNvLNlM0kVUQnm+a89c85sjgaQHr0AtFs8n32jsQpzvXeYVUGR4qLWX9r/wAxqKArAhU5WweYEHRBTXV/z79l2QShGFdk3hW9QZxzCYCXtzy14FeBt/8lvZkK3AMtPvrkD7ix74/LcY5hTW3KtUJDhSMhRlJB5q5W2+xuPPhkfzRiIUuoE67pp68DJ/fZu0OEK9zEpCIYV8BV3FYsvQYc1ATuAlNz4Nv/Y+OuP6d21sbcFPSdMQXLhu/hsieJPnKhCJ/f/Tff6DCv8H8hZgYwf60ymoV3rC7ggZ+G/Hy3Wcnze5eQHom5Pe8V6wN1TJwp1y4+TK+hLkKaOv6ukOwMuKW5cdqfgU5ReaDknOt2Zd2nek0CxCQLWEAhp0sqSY6TaBNsQNc5PaRVdZhYQyVj0aOcPBmblXubodz9vA/pkdcPprUR3xoV0H3DAcyL+dy25A1goh+ddWPr0sdCMcGQb6gmhXC5wg6qjNaRByMTRgWit+UjNVV1FrMNPJA4WxSOA3+jUjgzlxgGEJWepwOFwC162vUFunT+H4+9g+Nlni2LsoewQ5f0Uproc9KIp8vnbTUJ6UPaSccw0nimjZQ1XfMxyDDWaSSz1hncF4yQ8RUCVQx5blIdNXczsuwYA3GoAs9rIo="
        # Signing
        - secure: "jIY/85nbgevg4GbmH+LAhs7mzGYqkSynmUvxtQ2TJOUlEuo1ZPi4aICibrz4+CL4oXCX4qguZrpSW3LBlizdrH5kqytdhz7AH77t4SpUs9OKhL9CJu08oNt8VYUwS/Zib9Xs3S9u5CFnEJveJNd5Xe/3lKaWuMI6k59AqxueG2KFAf0uW3xr6Fpc9aQOBsfLzIE5f7cifuzVwlmhW3cnbOr//Wbyih++1pe0O4WnwtqsU+lyCAIrpK9PEFKYn9Sgpah0Wbjdh28f1WZMyQaGKGR3LFQmVaBCFhsp/j0VHJYHtAeUtrYsOJDsjUxJBHLF3cXK37nsUvIbN4hTlY2No/FrgIXWOJKn2B5YTnSXVmLdGCXKP214dLA2j0NPNT8G62075dSB+8vZPyARwH1WrRP39dkv140BVh2lh1WBYwKzIlH8dUD/TYKhBSDSxMkduqoE3Xrm5I0ZIU1Lh1++iWOqcGBkLNiRwDEKX9GZ8+dPYCJ+TEhW34eXnJz0IsfUjGU5nxVDF6ik5jq6CVVlfc/MJ550ABGGmIXO9we8GilgUEDaQ/Z+CPdb/LNRNEs+UtMqsZ74R5HYzkbEWQ/3jt1Bvy9psaa0II8YY+THs0I8uD0NNlgeJ4t7JTKaeptDYB9i5fWjkvX9E0B3BA9g3jt5jvF9BbhLV2PUIB2IVdY="
        # Plugin portal
        - secure: "Yz0vNipLkqdl1JujmlflCIfuHTQCUr/9Juy1FXWSgM/zSmQP5qQjkNR1HT9NBXRGEloqbChAyqWcykp9s3rt4LCZ6ljUAHUKnuvWPVlzBzsYuBU0kej1xFmb6TRlSMHL1upYJDGo3zqommJt60aHcG5vZkAqqoD2plWw/e5s/Z56Av3LVs/7oKeX2Sv59Jy3sdtHO5MlZ16wLPjaFhLDrx3KJHbmGnYPejB5f3k5haGidERg5XdpQ5cQVMgl9F+uEoPiysIoAZ99nRAjOHnrBfI42cHJynxispDntEdJdcFj+HE0LBaZSiLl4/YtRmspw/IdClqCum4dlczOUZzO95uRKnRaXTSQRtGH+pRGvauFMHw6ywQz11W06q33Ltf+ySl3zvE5RPCkUe5fOZWejQRz+H+LkJJ+u8v+Wg1AXtK04XSdD9L4qYwPIiRvf/YtRen1WXdXLF7qobOg/Mf/y9C1rEaGG2e3rCHuF9uoIsOQbKDyteFNhoTx9tQMr/4DBaCjqc75sbqgzxxJWcwIJ7V5KZSys5h2SddCUn5bBQ3HiMaZgkRAb9N1KG5T7DGwwaPsG4ZGKlR+LfgH1hezUOz6ZoELw0ypihSaWJn5FtEU69JXtJDOmK6aZ3rOHKnElcPh3UfWzsnNlIrGbGF5oVyznqs8vYN3xKXsoHqL6RU="
        - secure: "nArNcQSFf20GM6df7RaPzmfbYsP0igEiRdacO6SZMBZDX8bUaz5+88dPPCfmAhU3+l3Ez2yAJGOTK5DgfI0p2Ev7nnRBmnxPFHfIkuERdqoQZRqZuK5KKEtft2eSit2Iqq6Dq53j+TjuuVBxSKHgYh0LzzDQ7J8v48fia+W95j3/7ikrvYuo19yoX1E5HJye6Az6JsVhB2n68bseinGG1TIEvI+nfoh2++ghsfgoEpHcVtY0os5GoZ3MPHq50vpf08OhRFG0Ae5y0LXxTemoTXxLvfYjN0hosJ79FqZFsu67L4E5cwWgI4+9pS4WXUb1zIbVsX/eSkGsxesQ9ghTd8Mpziyeh7f9EGw7rBFuNiEO7LGHoTTqi9votpvpJvR/aN7OgC8JACj/JldAbEnBk0+G2KNNl2q6VfXIkJzhTTLbC7O24J/mqvY/EXJMrLN0rRkC+SbsBz7hLigGeTg+kq+ZNb5HWMWV6URG4LdZhQmJ55do+A/IOE7W0AbODitWh1v5SNCTDqHRIYnBTbVSrW48ZLHkXnBweMCv0FzW/sUkUyfAqO5jK3FS2hAsR0rDoJrTSlAjTKxlUsWsLK/MnPh9kwepR2/IX+ifBGBJlk7IgRJtS5kfThBdqPD/l/V5VQgkKHEQWQCIjq2zLAGk6kjkDr5ds50b9RtWNNPYKuE="
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_e7e03982aaff_key -iv $encrypted_e7e03982aaff_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew sourcesJar javadocJar sign
      after_success:
        - ./gradlew publishPlugins --stacktrace
        - ./gradlew publishMavenCentralPublicationToMavenRepository --stacktrace
before_install:
  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
  - source .disable-windows-defender.sh
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew clean test --scan --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - source .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
