reference_jdk: &reference_jdk
  'JDK="adopt@1.8"'
reference_os: &reference_os
  'linux'
language: bash
git:
  depth: false
os:
#  - osx
#  - windows
  - *reference_os
dist: bionic
addons:
  apt:
    packages:
    - graphviz
stages:
  - check
  - test
  - deploy
env:
  global:
    - secure: "f0fnxgVNlERe5SH+5TgknEM8Cf+EuI0HYvGIrCj5u7ZJslDHkEvcrD+KakPPdliORVamAe3vLczyO1ql9fKMZckgT13agj17XN9OGnExvU/mPUxu/nMQnWcXafy1nSWPYVyEmjm3/4VNbCOs/NJki2kUQXZJvzymIjhHGD/XGSxyzZ04QG/VEKMu1/D+f3EiRMWkHomTRK7VpVPFVSI3ueds55H7H2XIGL/X3zn9gJdtrdD3PHTpL6cyQuqnntgheL6k30WxBruoj3FlB3xm/nAoqWbYsvMH/3wPRGaMXmhxAzp7Qa6qvaO96d8TSxsvKkZJSupjSzi8ckjTf7/CVZ4xkOVKwia/Of+jtBHms74BBMEAuHYcqULcbTOzfWLNUizgnnchun1W+zSIYvaSU5e3mo5WAfbXddJ81SBoCBbDzrp1oNubTUmTAnFUQsdRuTfaSQk0YxAobvqhMO3+0lHC6sPAxQF3NZ/mebX/nPN9wm3tMKfVvLp08M/ChrzD7lsfVkg2MzQBB1n3qMz3vKMhYR/Qo7XsG4iUSFb2uWwGWU9WjOeNx4bKjITavX3aqXLaFQnF74CAsijf7E+lRKq5zGAi2XKO2QZ6wtw8FuAoeD3C84WxzhIrUNzNTKNOUkh0FwwSJ85Vsa0omvclsX3aNQXZ0yJSiy0ij70r5iI="
    - secure: "VKGZ0bakj7uoetLjRbSDK/kd9Mx7MSgy3KqI936FOAg0o0ZM5Xu0e6KTtqydmzP8aPrs7/Sceq1T8WHaF2kFZM2CXDRUkx79Ax4fB9j/IwfdIBortj2teCIzxjSM9QzMos7ePeYNB7/MzOwBshdkdNyWgjrblEim6yrzpqbpoeTE4slIkYS347W+Ze0vSL3KABoEVBCHgyENIm04wCMjjMR3hiQSaAnMHzlos0zfMwehlIEy0vnJuP15JEbl/QgX0ds2ZrrXW1vCI3kWsFmjaoFYXG6TyHZWI9j3vGx9HnMhYTsOm6OTL6ulRty+DiaK/pZwSt6x0e0RxrIoOsR/QgtRWVQpdBZwGmVBlPl/TdXCz+jASh2PN1y52e0wpJBu19c2SxjoqjKOqWRg2SeGwWe+SSaNs8acadu6ep6P4RYkIenP5X5bOGf65D2tjIF6Y5YlyA9I8FwIhyxPjUww33hAMwfSKSMDTGt1kYkaCK9iNt3JZZCtZdEOOKzH4uXAdQlEwU4VSFE/kiuo7tUonED1VDZNbpwR1x79OGyniggpUSrPmUPIA/jo3nd7UY1YKJjhxL0FHxNt9bYyRUbVzsnsOv5zVF+8JQNLnSitmr2zR0ARlufZB9Xj5XjO8Z5vZcxgTiwVp5aTOxN+tuuz+g26IAuivf3HqSPIGqLHb+I="
    - secure: "XHZA70J7+Z8XTC4iWsg/cdZhss2Ti4C5GhY74nUrFOQ8NERwpxlJlqiYM8ou8+tkt6GNQRCW9k5Sybx2X4aP2w8KRWVLu7hRnZl2ySJU7DeDC1P7uG2BFQiNPodsJw+X5JnHlvItuy15OZy8zEY39o6iSTEbq5goVln8xjcGzcY4mPkbdGPf2tPbXdxx71GE/KZf4IZVMWOg/sGbl2GKKkUTvI3A692PSHM7/YlKlKREaqNh5IHnATGiQKHr923UxkfS/zvIhfJq1VoWuPr7e11No431h4T0R4xcDKQeF+bzW+XiOeIQPz00DWncajoSKox6yZglAqD7Xw3y27+XJzsJutbDyReTxGA5y24Ri7Esdi05BE/2maDkYfPqU4BTJuqqN7RDb5OPF5RaI39ZnCN4M1rjTiZqeDjQ7p7XN21orKcdpw2+ImQ1SSIavufmO7aYBL98ekGnEd3BVaWoFIHkObtybd7QdHYOtSo1YgU72Ut5jpSLZywqtBVQo7Oj56U1zOk8gSJWdp0ZhDi4VHKoGD0HMf8PkpHOg1eG8dzZPLYmkeWquzrnxc7xZwSSkCwJbEl7Xod9blHC8gFnuUoZCsif0qICw8xz1HeLEHGZrgegP6L8gIx0WN2Yq+nmuq1BRPvMqjyaxZ7HY3YvMCRHN6tuX/lltBGwPbo1NPA="
    - secure: "GgP2GfDoKRpYIbN4pUzpY8V6hxwxGPpEyde7xnoxUdjDzpGZdfc2sf3P8PJ/yQKhmUr3ttAhzNoKh9KQDfoHQpOzcAEJLeb5IHkfPkosjvxMLbpdJP1tgCcDa5pfuKzNHk9Oj7m3lMwmd+cYDKTsYmUB1lg5SAOBvTZd+9ZSdW7gEZKfd3dnd2zRzfqwkBU+dMQpQIIGNrj5H8pTVA1ZUn71KV5wi/6W4c6ok2iP1KArwVGq9Oedey76FqJH0m2jgtA4352UIgDxX4gDlqiKMBUw65lXz2Mw4s1xd4rlpdFO7ra8px1HwzfIo6yLE6SPKEamXgfuRLs+70g9V6VK4YsGtobs4khgFWBM4YgDO7A1VfU0utxeinbYywIW+hk1QjIbuwIu0zU+S6HB27/AGlq11fIhAL8N6jtcBg+a51dMh65D4syGSZD5RpzFp+I3fNEzihdSBTh08t7Zb1zZGE2ZDPTmJOQuogbXcUEu6oFz/1cc4FoYE/9pyiT3fiDjj6GuM6HDm9zoWlMwhaA5TrI6OywxuBDDfPdhNrS/MNcC+aguFCpxJv9ZxzNJYG4S8SXlPwplxtG6G8cwEAfwZcdEI/b/Jy3BvOUN1Hu0e5eYxQ1wXkP3XZs7Va8Q5dtPZUvKSfWeHokGat85zVczWIPC4REdbiBoUDhzCeI9lc0="
    - secure: "Z3v62BxEmrVNUt/P0jQJPnvuq+aHM39lU6y4jmLcyeijSrzxHuXAhANz3+zQMCSOLdZQQ4wpA+XMrM5sRmw9ObSCrC9fIntzNMlE/JxS4QC4H0A7d738Pb0Lq3oqXUHtr5lKzVp1uIBLdbY7h0oIyTfAo0cVVmAlLf300DykzRZAHkIUCKaaeRkCwRh0ae9Rlvl/HeRabJNvxCIUrGr1lJAXw8zGVyQBQ3Qajh6r0dxEcodxrLneZRbrJBctdxle1BeT4V+ayEFUd9wg5IWBkmzw9u0CReACVjqs4QuugOBTz2vwiTq8vhoCGVzHyF8V5p4RtYXlgEvPJxNgo3wvBQapQhDn2PXYA6TDJIaP7SOeZBdy8aFt7KK8xIUQaDV8ov2ypbn/RMMuLKvYKzh5T1lrthQbf6aSt6Cz4AJI/h6D4O0qdPmeLkdRNt4K84bqnJxdfE8cPfjtOo3yrF9rUqIr/CaevdSuJ4UKUdKrX7qZUHyUCpebzogZ8HpiT5rWEfsa8LZlGJ/3WZoZmr0MSkR+JzthQLe3uzMlB3JAo/wSf2q6NJEJUGgewROg/CrjyFuU3tkbcULQKq/rHxlF8VunASU9YMEKDxZlTQlb91f78riAGmFv+I3ZPWCUtI2wwZ26MSppxNj8E/Cz9tho7rUg8FJ+ETjwWPewIKcizH4="
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - PUBLISH="false"
    - OFFICIAL_REPO_SLUG="DanySK/maven-central-gradle-plugin"
  matrix:
    - *reference_jdk
#    - JDK="adopt-openj9@1.8"
#    - JDK="adopt@1.11"
#    - JDK="adopt-openj9@1.11"
#    - JDK="adopt@1.12"
matrix:
  exclude:
    - os: *reference_os
      env: *reference_jdk
jobs:
  include:
    - stage: check
      name: "Deep check on reference OS and JDK"
      os: *reference_os
      env:
        - *reference_jdk
      script:
        - ./gradlew clean check
    - stage: deploy
      name: "Reports and deployment"
      if: repo = env(OFFICIAL_REPO_SLUG) AND type != pull_request
      os: *reference_os
      env:
        - secure: "GIBSVMLxO13RGCizxjkgU5uWIBqWviPJCVIIa+ElbBGJs4v7FUVDDQHCEEoJvQjDElxDiXLhFAPQF/+00+EAMru3FcWuN436kQWJ5cxiTCErEj2WqTxFe+cIhHX+ASCZfSa74bJkBOJgGnfyrGJoyzDIv80ffZrwm55Tyy7K66f4+e2Ifrl3HB8v83etvF+g693+m5T8BytnOZRsa2vy0ZhRH7LOhgNro52r1KIj3xHb+0/qmNaDlZYqOcFJ8/OU9ezfyGk6zcNj8j6RkT2f874Swu3iyL6O+Kfo1pwGMNeQ2YeVXRpl/5na85A0GXnAUFFmRtLviJR0c6/l6jpq6Uxf0SCjtecKlpjWwUd1m7FQ6P/jfpNsW1quzIwGcA/lFrgjGfX2JuYqV1VSUzPu1ko7BG42u6rrRzSEiUTlvmMpC6xBktrR8U6mGlBxRxsL8nDlqrI1R5N6fjla/maCxLVgDeQOzvFO6AuGagtgFq1mOazGmy2yrDxNSeYU912ZHMPmkQlce979uR/lVxNDVF4FKOVeg6/hSNqy3XC1cO6MJGiQKCo6rL9ykpwYqcj3TckRd5u0XqTJsSV3eifStCNLulSKAAdzQMrelsiHEMHJI2VU/wwCc4bSvXmeji68MjqXXalajEl7fpVXT/wmOuh1jUSEP6nzA957OXj4Pho="
        - secure: "JqYCzozZ6pWU44QyK2DStXWGZCXz1i2eKgNDwxSeiBwp6ZJzTfkLQTKQbmD1r1qLqNaZ8pb2++FfpMNimSByM01kBvqF9wL+NFZOo7KMaOPVlOn3Xm3wzmOZD0lO4NP62eUHOUwsXLhfeilOqQFbSRuta2D3p3zKe6HAMDm9vZIHeAUxcJB5wdyssg5IZRKYAeGH4yCkjugZ192acd4ahMhJd7K08DH+VMGiXAuXMTjjCMFwQEAPHBwTGY74O/fZKnF8LRWaGCwL2tA21yJvXyUUqY0dstJElIfFcEbDYIgBO9XTu5W1Z++kGF8AyigRf7HLMUWt+ja9APYx/riImR6l/4TamZ33klPfHjhhXNdRovrlWAoOLIQYIXvi+Ouxujgt+tXzrQpu3FEdhN0faG88xgsQyOuxf5qmv3RLHytfk7yZosThnGI7Ys5y+ocfi2c3PVltr61Ege1xPvnsqHeZ0LfJxZ5btWPzOKXkziLeETpBekyfKVoyzER3m6vvsfT56GemSegxGs+Qz5OHQNS2eqADb5zepsicMJ1tysCPSHmihzFiM+tcCzz9vD70fLNgMDcCgoiMKJoSM1HRmbhYIfUCvu/esEWJiNL7IMGoWTlA9brctlIRy4UgkrBsTvh4gnBg2WH+GBlpNSdAiWJXqsCVW3wnjKr8k0fuqbQ="
        - secure: "jIY/85nbgevg4GbmH+LAhs7mzGYqkSynmUvxtQ2TJOUlEuo1ZPi4aICibrz4+CL4oXCX4qguZrpSW3LBlizdrH5kqytdhz7AH77t4SpUs9OKhL9CJu08oNt8VYUwS/Zib9Xs3S9u5CFnEJveJNd5Xe/3lKaWuMI6k59AqxueG2KFAf0uW3xr6Fpc9aQOBsfLzIE5f7cifuzVwlmhW3cnbOr//Wbyih++1pe0O4WnwtqsU+lyCAIrpK9PEFKYn9Sgpah0Wbjdh28f1WZMyQaGKGR3LFQmVaBCFhsp/j0VHJYHtAeUtrYsOJDsjUxJBHLF3cXK37nsUvIbN4hTlY2No/FrgIXWOJKn2B5YTnSXVmLdGCXKP214dLA2j0NPNT8G62075dSB+8vZPyARwH1WrRP39dkv140BVh2lh1WBYwKzIlH8dUD/TYKhBSDSxMkduqoE3Xrm5I0ZIU1Lh1++iWOqcGBkLNiRwDEKX9GZ8+dPYCJ+TEhW34eXnJz0IsfUjGU5nxVDF6ik5jq6CVVlfc/MJ550ABGGmIXO9we8GilgUEDaQ/Z+CPdb/LNRNEs+UtMqsZ74R5HYzkbEWQ/3jt1Bvy9psaa0II8YY+THs0I8uD0NNlgeJ4t7JTKaeptDYB9i5fWjkvX9E0B3BA9g3jt5jvF9BbhLV2PUIB2IVdY="
        - PUBLISH="true"
        - *reference_jdk
      install:
        - openssl aes-256-cbc -K $encrypted_e7e03982aaff_key -iv $encrypted_e7e03982aaff_iv -in secrets.asc.enc -out secrets.asc -d
        - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
        - rm secrets.asc
      script:
        - ./gradlew sourcesJar javadocJar sign
      after_success:
        - ./gradlew publishPlugins publish --stacktrace
before_install:
  - curl "${GRAVIS}.disable-windows-defender.sh" --output .disable-windows-defender.sh
  - source .disable-windows-defender.sh
  - curl "${GRAVIS}.install-jdk-travis.sh" --output .install-jdk-travis.sh
  - source .install-jdk-travis.sh
script:
  - ./gradlew clean test --scan --parallel
before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - source .clean_gradle_cache.sh
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
